name: Test

on:
  pull_request:
    branches: [main, v4-v2]

jobs:
  docs-build:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - run: npm ci
        working-directory: docs

      - run: npm run build
        working-directory: docs
